name: build-firefox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.18    
    steps:
      - name: Install sdk
        run: |
          apk upgrade
          apk add alpine-sdk sudo  
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
          ref: v3.18.0
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
          adduser builder -D -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild
          chown builder -R ..
          chown builder -R /tmp
          mkdir -p /var/cache/distfiles
          chmod a+w /var/cache/distfiles
          chgrp abuild /var/cache/distfiles
          chmod g+w /var/cache/distfiles
          su builder -c "abuild-keygen -a -i -n"
      - name: Move repo directory
        run: |
           mv aports/community/firefox /home/builder
           chown builder -R /home/builder
           cd /home/builder/firefox
           sed -i 's/113.0/113.0.2/g' APKBUILD
           sed -i '/0001-Bug-1831691/d' APKBUILD
           sed -i 's/96b0f0774083270f4fcce06085b177ced25ba05da7291d777f1da1d5bbad30721bc6363b76e06ccb64fc092778c8326a426a8bfdfa3cbaafd4f1169b924744a5/7b1ff7d547fda02901f54a2593e03598a830698192003d833e27b85db0e00571ff66e03ebd4089e76fa65b09df000cbb2542450beeabb0b310875910603e6743/g' APKBUILD
#           sed -i 's/ffmpeg-libavcodec/ffmpeg-libs/g' APKBUILD
#           sed -i 's/lld15/lld/g' APKBUILD
#           sed -i 's/clang15/clang-dev/' APKBUILD
#           sed -i 's/"clang-15"/"clang"/g' APKBUILD
#           sed -i 's/"clang++-15"/"clang++"/g' APKBUILD
#           sed -i 's/111.0.1/112.0/g' APKBUILD
#           sed -i 's/b16c9399a19cb1de2d865a023d54fbe71c23a363ea4d36cd58f41f64f7ad04bc1b9d8a8448943417516e17337e0ee2afd370c29a72b51b0947161f4ffab6935f/6b2bc8c0c93f3109da27168fe7e8f734c6ab4efb4ca56ff2d5e3a52659da71173bba2104037a000623833be8338621fca482f39f836e3910fe2996e6d0a68b39/g' APKBUILD
#           sed -i 's/pkgrel=2/pkgrel=0/g' APKBUILD
#           sed -i 's/_releasedate=2023-03-21/_releasedate=2023-04-11/g' APKBUILD
#           sed -i '/python3.11.patch/d' APKBUILD
      - name: Install packages
        run: |
           cd /home/builder/firefox
           su builder -c "abuild checksum"
           su builder -c "abuild deps"
#           sed -i 's/v3.17/edge/g' /etc/apk/repositories
#           apk update
#           apk add rust=$(apk list rust | grep -v installed | awk -F"[- ]" '{print $2"-"$3}') nss=$(apk list nss | grep -v installed | awk -F"[- ]" '{print $2"-"$3}')
#           sed -i 's/edge/v3.17/g' /etc/apk/repositories
      - name: Build apk
        run: |
           cd /home/builder/firefox
           su builder -c "abuild"        
           cp $(find /home/builder -name firefox*.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: /tmp/*.apk
