name: sample-action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.17    
    steps:
      - name: Install sdk
        run: apk add alpine-sdk sudo  
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
          ref: 3.17-stable
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
          adduser builder -D -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          addgroup builder abuild
          chown builder -R ..
          chown builder -R /tmp
          mkdir -p /var/cache/distfiles
          chmod a+w /var/cache/distfiles
          chgrp abuild /var/cache/distfiles
          chmod g+w /var/cache/distfiles
          su builder -c "abuild-keygen -a -i -n"
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: alpinelinux/aports
      - name: Move repo directory
        run: |
           mv community/firefox /home/builder
           chown -R builder:builder /home/builder
      - name: Build apk
        run: |
           su builder -c "abuild-keygen -a -i -n"
           cd /home/builder/firefox
           su builder -c "abuild checksum"
           su builder -c abuild        
           cp $(find /home/builder -name firefox*.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: /tmp/*.apk
