name: sample-action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: registry.gitlab.com/mtak-misc/sample:test
      credentials:
         username: ${{ secrets.user }}
         password: ${{ secrets.token }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: alpinelinux/aports
      - name: Move repo directory
        run: |
           mv community/firefox /home/builder
           chown -R builder:builder /home/builder
      - name: Build apk
        run: |
           su builder -c "abuild-keygen -a -i -n"
           cd /home/builder/firefox
           su builder -c "abuild checksum"
           su builder -c abuild        
           cp $(find /home/builder -name firefox*.apk) /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: /tmp/*.apk
