name: sample-action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.17    
    steps:
      - name: Checkount aports repository
        uses: actions/checkout@v3  
        with:
          repository: alpinelinux/aports
          ref: 3.17-stable
          path: aports
      - name: Prepare abuild
#          echo "permit nopass :wheel" >> /etc/doas.d/doas.conf      
        run: |
           grep pkgrel aports/community/firefox/APKBUILD
